# Site settings
title: NomadicRiz
description: Offbeat & Budget Travel with Infographics
baseurl: "" # The subpath of your site, e.g. /blog. Set to "" for root.
url: "" # The base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima # You can keep this, but your custom CSS will override its styling
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/